### ISSUE TITLE
Printer Flash Not Working For Me

### ISSUE THREAD

**Issue by SwiftCookie** [fryc88/klipper-sv06plus-screen#5]
>BUT when you go to your Moonraker GUI, you will see DIRTY/INVALID red message next to Klipper & it will refuse to update

This didn't happen to me, it still said everything was fine

-

>Klipper needs to know which UART is being used for the screen

I have no screen serial listed here.
![Untitled](https://github.com/fryc88/klipper-sv06plus-screen/assets/139315674/f942da6a-35af-48f4-8689-b0dfc1a1b166)

-

>You will see something similar at end, most important is last line of it, that means our bin file with klipper has been created successfully:

Mine says "Creating hex file out/klipper.elf.hex" instead of .bin
![Untitled1](https://github.com/fryc88/klipper-sv06plus-screen/assets/139315674/b9c418bb-778a-400b-87fb-880ba1f63c13)

-

Now I'm stuck here:
![Untitled3](https://github.com/fryc88/klipper-sv06plus-screen/assets/139315674/48705512-e8fc-4b8a-9599-5e164c817cd9)

I tried changing the out/klipper.elf.hex file to out/klipper.bin and flash the printer but it's still not seen by mainsail. I don't understand what I've done wrong as I followed your instructions exactly, please help :(

**Comment by fryc88** [comment]
Go through my guide again, following it step by step, no skipping steps. I can already see you've missed quite many steps from it.

**Comment by SwiftCookie** [comment]
> Go through my guide again, following it step by step, no skipping steps. I can already see you've missed quite many steps from it.

I only showed you my issues, not all the steps I also did. I literally did every step.

**Comment by fryc88** [comment]
Unfortunately you did not. You haven't set anything in make menuconfig and exact settings are shown on the screenshot in my guide, that's for start.

**Comment by SwiftCookie** [comment]
> Unfortunately you did not. You haven't set anything in make menuconfig and exact settings are shown on the screenshot in my guide, that's for start.

Sorry I fixed that step, I didn't realise those expanded when you select them. 

How come I didn't get that Klipper INVALID error in Mainsail? Mine still said up to date.

My final problem is that I've got the screen on and it beeps again but it's still the old menu (bugged) and not the new Klipper one. I successfully flashed your supplied screen firmware to the screen board and added the entire screen config to the printer.cfg.

**Comment by fryc88** [comment]
If menu in the screen hasn't changed - still shows sovol splash screen instead of klipper, that means screen has not been flashed correctly. These screens are a bit temperamental regarding SD cards, that's why I suggested to use stock card added to printer, these works just fine.
With klipper & dirty you might need to refresh updates just by pressing round with arrows button in your web browsers GUI of klipper and it should come up as dirty.

**Comment by SwiftCookie** [comment]
> If menu in the screen hasn't changed - still shows sovol splash screen instead of klipper, that means screen has not been flashed correctly. These screens are a bit temperamental regarding SD cards, that's why I suggested to use stock card added to printer, these works just fine.

I've tried two SD cards now, the stock one and a 16gb one. Doesn't seem to be installing correctly as all my numbers are 000. 

![PXL_20230718_223819590](https://github.com/fryc88/klipper-sv06plus-screen/assets/139315674/19b9cd3c-537d-46c4-904e-e897ef74440a)

**Comment by fryc88** [comment]
Yes, it is not flashing it. Either because of card or you have extracted files wrongly.

**Comment by SwiftCookie** [comment]
> If menu in the screen hasn't changed - still shows sovol splash screen instead of klipper, that means screen has not been flashed correctly. These screens are a bit temperamental regarding SD cards, that's why I suggested to use stock card added to printer, these works just fine. With klipper & dirty you might need to refresh updates just by pressing round with arrows button in your web browsers GUI of klipper and it should come up as dirty.

I used the stock 8GB sd card and it said it flashed properly 

> Yes, it is not flashing it. Either because of card or you have extracted files wrongly.

I'm not sure how else to extract them haha

**Comment by SwiftCookie** [comment]
> Yes, it is not flashing it. Either because of card or you have extracted files wrongly.

Must have been a formatting issue, I tried a couple different methods and that fixed it. It has flashed now :) Thanks for your help mate!
